# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Maven Package and Docker Build and Test

on:
  push:
    branches:
    - main


jobs:
  maven:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        cache: 'maven'

    - name: Build with Maven
      run: ./mvnw package
    
    - name: Upload artifact to Docker job
      uses: actions/upload-artifact@v3
      with:
        name: java-app
        path: '${{github.workspace}}/target/*.jar'
        
  docker-build-and-publish:

    runs-on: ubuntu-latest
    needs: maven
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Download artifact from Maven job
      uses: actions/download-artifact@v3
      with:
        name: java-app
    - name: Logging in to Docker
      run: docker login ghcr.io -u htom70 -p ${{ github.token }}
    - name: Build the Docker image
      run: docker build . -t ghcr.io/htom70/cubix/1/homework/app:springboot
    - name: Publishing the Docker image
      run: docker push ghcr.io/htom70/cubix/1/homework/app:springboot

  docker-verify:

    runs-on: ubuntu-latest
    needs: docker-build-and-publish
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Verify Docker image
      run: ./verify-image.sh
    
